src/DocBlog/urls.py
from django.contrib import admin
from django.urls import path, include
from DocBlog import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('blog.urls')),
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

src/blog/urls.py
from django.urls import path
from .views import BlogHome, BlogCreate, BlogUpdate, BlogDetail, BlogDelete
from django.contrib.auth.decorators import login_required

app_name = "posts"

urlpatterns = [
    path('', BlogHome.as_view(), name='Home'),
    #restreindre l'accès
    # path('create/', login_required(BlogCreate.as_view()), name='create'),
    path('create/', BlogCreate.as_view(), name='create'),
    path('<str:slug>/', BlogDetail.as_view(), name='detail'),
    path('edit/<str:slug>/', BlogUpdate.as_view(), name='edit'),
    path('delete/<str:slug>/', BlogDelete.as_view(), name='delete'),
]

src/blog/models.py
from typing import Iterable, Optional
from django.db import models
from django.contrib.auth import get_user_model

from django.template.defaultfilters import slugify
from django.urls import reverse

# réccupérer le model utilisateur
User = get_user_model()

class BlogPost(models.Model):
    title = models.CharField(max_length=255, unique=True, verbose_name='Titre')
    slug = models.SlugField(max_length=255, unique=True, blank=True)
    author = models.ForeignKey(User, on_delete=models.SET_NULL, null=True, blank=True)
    last_updated = models.DateTimeField(auto_now=True)
    created_on = models.DateField(blank=True, null=True)
    published = models.BooleanField(default=False, verbose_name='Publié')
    content = models.TextField(blank=True, verbose_name='Contenu')
    image = models.ImageField(blank=True, upload_to='blog')
    
    class Meta:
        #affiche les artiles avec date de création
        ordering = ['-created_on']
        verbose_name = "Article"
        
    # avoir un affichage avec le nom de l'article
    def __str__(self):
        return self.title
        
    def save(self, *args, **kwargs):
        if not self.slug:
            self.slug = slugify(self.title)
        
        super().save(*args, **kwargs)
        
    @property
    def author_or_default(self):
        return self.author.username if self.author else "auteur inconu"
    
    def get_absolute_url(self):
        return reverse('posts:Home')

src/blog/views.py
from typing import Any
from django.db.models.query import QuerySet
from django.shortcuts import render
from django.urls import reverse_lazy

from django.contrib.auth.decorators import login_required
from django.utils.decorators import method_decorator

from django.views.generic import ListView, CreateView, UpdateView, DetailView, DeleteView
from .models import BlogPost

class BlogHome(ListView):
    model = BlogPost
    context_object_name = 'posts'
    template_name = 'blog/liste.html'
    
    def get_queryset(self):
        queryset = super().get_queryset()
        #vérifie la requête en cour
        if self.request.user.is_authenticated:
            return queryset
        
        return queryset.filter(published = True)

#restreindre l'accès
@method_decorator(login_required, name='dispatch')
class BlogCreate(CreateView):
    model = BlogPost
    template_name = "blog/createBlog.html"
    fields = ['title', 'content',]
    
class BlogUpdate(UpdateView):
    model = BlogPost
    template_name = 'blog/UpdateBlog.html'
    fields = ['title', 'content', 'published']

class BlogDetail(DetailView):
    model = BlogPost
    context_object_name = "posts"
    
class BlogDelete(DeleteView):
    model = BlogPost
    success_url = reverse_lazy('posts:Home')
    context_object_name = "posts"

src/blog/templates/blog/UpdateBlog.html
{% extends 'base.html' %}

{% block title %}
    <title> Modifier un Article </title>
{% endblock %}

{% block content %}
    <h1>Modifier un article</h1>
    <form method="POST">
        {% csrf_token %}
        {{ form }}
        <input type="submit" value="Editer" class="btn btn-submit">
    </form>
{% endblock %}

src/blog/templates/blog/blogpost_confirm_delete.html
{% extends 'base.html' %}

{% block title %}
    <title>Supprimer un article</title>
{% endblock %}

{% block content %}

    <form method="POST">
        {% csrf_token %}
        <p>Êtes-vous sûr de vouloir supprimer "{{ posts }}"?</p>

        <input type="submit" value="Supprimer" class="btn btn-delete">
    </form>

{% endblock %}

src/blog/templates/blog/blogpost_detail.html
{% extends 'base.html' %}

{% block title %}
    <title>Detail de L'article</title>
{% endblock %}

{% block content %}
    <article class="post-detail">
        <h2> {{ posts.title }} </h2>
        <h5>Publié par <i> {{ posts.author.username }} </i> le {{ posts.created_on|date:'j F Y' }}</h5>
        <img src="{{ posts.image.url }}" alt="Image de l'article">
        <p> {{ posts.content|safe }} </p>
    </article>
{% endblock %}

src/blog/templates/blog/createBlog.html
{% extends 'base.html' %}

{% block title %}
    <title> Créer un Article </title>
{% endblock %}

{% block content %}
    <h1>Ajouter un article</h1>
    <form method="POST">
        {% csrf_token %}
        {{ form }}
        <input type="submit" value="Créer">
    </form>
{% endblock %}

src/blog/templates/blog/liste.html
{% extends 'base.html' %}

{% block title %}
    <title>Accueil du blog</title>
{% endblock %}

{% block content %}
    <h1>Le Blog De Docstring</h1>
    {% for i in posts %}
        <article>
            <div class="post-title">
                <h2> {{ i.title }} </h2>

                <div>
                    {% if request.user.is_authenticated %}
                        <a href="{% url 'posts:edit' slug=i.slug %}">Editer</a>
                        <a href="{% url 'posts:delete' slug=i.slug %}">Supprimer</a>
                    {% endif %}
                </div>
            </div>
            <h5 class="post-author">Publié par <i> {{ i.author.username }} </i> le {{ i.created_on|date:'j F Y' }}</h5>
            <p class="post-content"> {{ i.content|safe|truncatewords:20 }} </p>
            <a href="{% url 'posts:detail' slug=i.slug %}">
                <button class="btn btn-submit">Lire l'article</button>
            </a>
        </article>
    {% endfor %}

{% endblock %}

src/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="fr">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    {% block title %}
    <title>Articles De Blog</title>
    {% endblock %}
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
</head>
<body>

    <nav>
        <a href="{% url 'posts:Home' %}">Accueil</a>
        {% if request.user.is_authenticated %}
        <a href="{% url 'posts:create' %}">Ajouter un article</a>
        {% endif %}
    </nav>
    <section id="blog">
        {% block content %}
        {% endblock %}
    </section>
</body>